[package]
name = "decision_tree_contract"
version = "0.1.0"

# Cairo configuration
[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true

[lib]
sierra = true
casm = true